apiVersion: v1
name: keycloak-db
description: keycloak-db chart that runs on kubernetes
version: 1.0.4
keywords:
  - keycloak-db
  - kubernetes
home: https://github.com/stakater/chart-keycloak
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io