keycloak:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 3.2.0
  namespace: tools
  image:
    name: fabric8/keycloak-postgres
    tag: "v15751c8"
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress
    forceSslRedirect: "true"
  config:
    database:
      host:
      name:
      username:
      password:
    user:
    password:
    clientSecret:
    privateKey:
    publicKey:
    realm: |-
      {}
  forecastle: {}
    # icon: https://cdn-images-1.medium.com/max/521/0*D__TQ7qMdoq3Y7kP.png
    # expose: "true"