{{- if .Values.keycloakdbstorage.pv.enabled -}}
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: keycloak-db-postgresql-data
  spec:
    capacity:
      storage: {{ .Values.keycloakdbstorage.capacity }}
    accessModes:
      - ReadWriteOnce
    nfs:
      server: {{ .Values.keycloakdbstorage.efs.server }}
      path: "/keycloak-db-postgresql-data"
{{- end }}