---
apiVersion: v1
kind: List
items:
  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      labels:
{{ include "keycloak-db-storage.labels.stakater" . | indent 8 }}
{{ include "keycloak-db-storage.labels.chart" . | indent 8 }}
      name: {{ template "keycloak-db-storage.name" . }}
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: {{ .Values.keycloakdbstorage.capacity }}
      {{- if .Values.keycloakdbstorage.pv.enabled }}
      volumeName: keycloak-db-postgresql-data
      {{- else }}
      storageClassName: {{ .Values.keycloakdbstorage.storageClassName }}
      {{- end }}
