---
apiVersion: v1
kind: List
items:
  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      labels:
{{ include "labels.stakater" . | indent 8 }}
{{ include "labels.chart" . | indent 8 }}
      name: {{ template "name" . }}
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: {{ .Values.keycloakdbStorage.capacity }}
      volumeName: keycloak-db-postgresql-data
