apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "keycloak-db.labels.stakater" . | indent 4 }}
{{ include "keycloak-db.labels.chart" . | indent 4 }}
  name: {{ template "keycloak-db.name" . }}
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
{{ include "keycloak-db.labels.selector" . | indent 4 }}
  type: ClusterIP
