apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
{{ include "labels.selector" . | indent 4 }}
  type: ClusterIP
