---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      expose.config.fabric8.io/apiserver-url-key: apiserver.url
      expose.service-key.config.fabric8.io/keycloak: keycloak.url
      expose.service-key.config.fabric8.io/jenkins: jenkins.url
      expose-no-path.service-key.config.fabric8.io/auth: auth.url
    labels:
      app: {{ template "name" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      provider: fabric8
      project: keycloak
      version: 1.0.2
      group: io.fabric8.apps
    name: {{ template "name" . }}
  data:
    db.url: keycloak-db
    db.port: "5432"
    apiserver.url: http://kubernetes
    jenkins.url: http://jenkins
    keycloak.url: http://keycloak
    auth.api.url: http://auth
    fabric8-realm.json: |-
      {
        "realm": "fabric8",
        "enabled": true,
        "loginTheme": "fabric8",
        "privateKey": "${KEYCLOAK_PRIVATEKEY}",
        "publicKey": "${KEYCLOAK_PUBLICKEY}",
        "sslRequired": "external",
        "accessTokenLifespan" : 2592000,
        "accessTokenLifespanForImplicitFlow" : 1296000,
        "ssoSessionIdleTimeout" : 2592000,
        "accessCodeLifespanUserAction" : 36000,
        "accessCodeLifespanLogin" : 2592000,
        "ssoSessionMaxLifespan" : 2592000,
        "offlineSessionIdleTimeout" : 2592000,
        "accessCodeLifespan" : 60,
        "clients": [
          {
            "clientId": "fabric8-online-platform",
            "enabled": true,
            "standardFlowEnabled": true,
            "implicitFlowEnabled": false,
            "directAccessGrantsEnabled": true,
            "authorizationServicesEnabled" : true,
            "fullScopeAllowed": true,
            "serviceAccountsEnabled": true,
            "clientAuthenticatorType": "client-secret",
            "secret": "${KEYCLOAK_CLIENTID_SECRET}",
            "publicClient" : true,
            "adminUrl" : "",
            "baseUrl" : "",
            "redirectUris": [
              "http://localhost:8080/api/login/*",
              "${AUTH_URL}*",
              "${WIT_URL}*",
              "${JENKINS_URL}/securityRealm/finishLogin",
              "${KEYCLOAK_URL}/*"
            ],
            "webOrigins": [
              "*"
            ],
            "defaultRoles": ["uma_protection"],
            "authorizationSettings" : {
              "allowRemoteResourceManagement" : true,
              "policyEnforcementMode" : "ENFORCING",
              "scopes" : [ {
                "name" : "read:space"
                }, {
                "name" : "admin:space"
              } ]
            }
          },
          {
            "clientId": "che",
            "enabled": true,
            "redirectUris": [
              "*"
            ],
            "implicitFlowEnabled": false,
            "directAccessGrantsEnabled": true,
            "publicClient": true,
            "protocol": "openid-connect",
            "fullScopeAllowed": true
          }
        ],
        "users": [{
           "username": "service-account-fabric8-online-platform",
           "enabled": true,
           "totp": false,
           "emailVerified": false,
           "email": "service-account-fabric8-online-platform@placeholder.org",
           "serviceAccountClientId": "fabric8-online-platform",
           "credentials": [],
           "disableableCredentialTypes": [],
           "requiredActions": [],
           "realmRoles": ["offline_access", "uma_authorization"],
           "clientRoles": {
              "realm-management": ["view-users", "manage-authorization"],
              "broker": ["read-token"],
              "fabric8-online-platform": ["uma_protection"],
              "account": ["manage-account", "view-profile"]
           },
           "groups": []
        }],
        "clientScopeMappings": {
          "realm-management": [
              {
                  "client": "fabric8-online-platform",
                  "roles": ["view-users"]
              },
              {
                  "client": "fabric8-online-platform",
                  "roles": ["manage-authorization"]
              }
          ],
          "broker": [
              {
                  "client": "fabric8-online-platform",
                  "roles": ["read-token"]
              }
          ]
        },
        "roles" : {
          "realm" : [
            {
              "name": "read:space",
              "description": "Read space"
            },
            {
              "name": "admin:space",
              "description": "Admin space"
            }
          ]
        },
        "identityProviders": [
          {
            "alias" : "github",
            "providerId" : "github",
            "enabled": true,
            "updateProfileFirstLogin" : "true",
            "storeToken" : "true",
            "trustEmail": true,
            "addReadTokenRoleOnCreate" : true,
            "config": {
              "hideOnLoginPage": "${HIDE_GITHUB_BTN}",
              "clientSecret": "2423ccccc0d286c45aff17cb8d303a7b41fdd748",
              "clientId": "46cafe0fb42bc59b9810",
              "defaultScope": "admin:repo_hook read:org repo user gist",
              "useJwksUrl": "true"
            }
          }
        ],
        "identityProviderMappers" : [
          {
            "name" : "approved",
            "identityProviderAlias" : "github",
            "identityProviderMapper" : "hardcoded-attribute-idp-mapper",
            "config" : {
              "attribute.value" : "true",
              "attribute" : "approved"
            }
          }
        ]
      }
