---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      expose.config.fabric8.io/apiserver-url-key: apiserver.url
      expose.service-key.config.fabric8.io/keycloak: keycloak.url
      expose.service-key.config.fabric8.io/jenkins: jenkins.url
      expose-no-path.service-key.config.fabric8.io/auth: auth.url
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}
  data:
    db.name: {{ .Values.keycloak.config.database.name }}
    db.url: {{ .Values.keycloak.config.database.host }}
    db.port: {{ .Values.keycloak.config.database.port }}
    db.vendor: {{ .Values.keycloak.config.database.vendor }}
    apiserver.url: http://kubernetes
    jenkins.url: http://jenkins
    keycloak.url: http://keycloak
    auth.api.url: http://auth
    #TODO: Update keycloak config and remove fabric8 traces
    fabric8-realm.json: |-
{{ .Values.keycloak.config.realm | indent 6 }}
