---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      configmap.reloader.stakater.com/reload: {{ template "name" . }}
      secret.reloader.stakater.com/reload: {{ template "name" . }}
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}
  spec:
    replicas: 1
    selector:
      matchLabels:
{{ include "labels.selector" . | indent 8 }}
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          pod.alpha.kubernetes.io/init-containers: null
          pod.beta.kubernetes.io/init-containers: null
        labels:
{{ include "labels.selector" . | indent 10 }}
      spec:
        initContainers:
        - name: envvar-substitution
          image: fabric8/envsubst-file:1.0.0
          imagePullPolicy: IfNotPresent
          args:
          - "realm.json"
          env:
          - name: AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: {{ template "name" . }}
                key: auth.api.url
          - name: JENKINS_URL
            valueFrom:
              configMapKeyRef:
                name: {{ template "name" . }}
                key: jenkins.url
          - name: KEYCLOAK_URL
            valueFrom:
              configMapKeyRef:
                name: {{ template "name" . }}
                key: keycloak.url
          - name: KEYCLOAK_PRIVATEKEY
            valueFrom:
              secretKeyRef:
                name: {{ template "name" . }}
                key: kc.private.key
          - name: KEYCLOAK_PUBLICKEY
            valueFrom:
              secretKeyRef:
                name: {{ template "name" . }}
                key: kc.public.key
          - name: KEYCLOAK_CLIENTID_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "name" . }}
                key: kc.clientid.secret
          - name: K8S_API_SERVER
            valueFrom:
              configMapKeyRef:
                name: {{ template "name" . }}
                key: apiserver.url
          - name: HIDE_OPENSHIFT_BTN
            value: "true"
          - name: HIDE_GITHUB_BTN
            value: "false"
          volumeMounts:
          - name: keycloak-config
            mountPath: /workdir/realm.json
            subPath: config/realm.json
          - name: keycloak-subst-config
            mountPath: /processed
        - name: init-dependencyservice
          image: fabric8/fabric8-dependency-wait-service:v6632df1
          command: ['sh', '-c', 'fabric8-dependency-wait-service-linux-amd64 postgres://keycloak@keycloak-db:5432']
          imagePullPolicy: IfNotPresent
          env:
          - name: DEPENDENCY_POLL_INTERVAL
            value: "1"
          - name: DEPENDENCY_LOG_VERBOSE
            value: "true"
        - name: git-cloner
          image: "{{ .Values.keycloak.theme.gitimage.name }}:{{ .Values.keycloak.theme.gitimage.tag }}"
          imagePullPolicy: {{ .Values.keycloak.theme.gitimage.pullPolicy }}
          env:
          - name: REPO_LINK
            value: {{ .Values.keycloak.theme.repo.link }}
          - name: REPO_BRANCH
            value: {{ .Values.keycloak.theme.repo.branch }}
          volumeMounts:
          - name: gitrepo
            mountPath: /repository
          - name: git-ssh
            mountPath: /key/id_rsa
            subPath: id_rsa
        containers:
        - args:
          - -b $(INTERNAL_POD_IP)
          - -Djgroups.bind_addr=global
          - -Djboss.node.name=$(INTERNAL_POD_IP)
          - -Dkeycloak.migration.action=import
          - -Dkeycloak.migration.provider=dir
          - -Dkeycloak.migration.dir=/opt/jboss/keycloak/standalone/configuration/import/
          - -Dkeycloak.migration.strategy=IGNORE_EXISTING
          env:
          - name: POSTGRES_HOSTNAME
            valueFrom:
              secretKeyRef:
                key: db.host
                name: {{ template "name" . }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: db.user
                name: {{ template "name" . }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db.password
                name: {{ template "name" . }}
          - name: OPERATING_MODE
            value: standalone
          - name: POSTGRES_PORT_5432_TCP_ADDR
            valueFrom:
              secretKeyRef:
                key: db.host
                name: {{ template "name" . }}
          - name: INTERNAL_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KEYCLOAK_USER
            valueFrom:
              secretKeyRef:
                key: kc.user
                name: {{ template "name" . }}
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                key: kc.password
                name: {{ template "name" . }}
          - name: KEYCLOAK_CLIENTID_SECRET
            valueFrom:
              secretKeyRef:
                key: kc.clientid.secret
                name: {{ template "name" . }}
          - name: KEYCLOAK_PRIVATEKEY
            valueFrom:
              secretKeyRef:
                key: kc.private.key
                name: {{ template "name" . }}
          - name: KEYCLOAK_PUBLICKEY
            valueFrom:
              secretKeyRef:
                key: kc.public.key
                name: {{ template "name" . }}
          - name: HIDE_OPENSHIFT_BTN
            value: "true"
          - name: HIDE_GITHUB_BTN
            value: "false"
          image: "{{ .Values.keycloak.image.name }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /auth
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 60
          name: {{ template "name" . }}
          readinessProbe:
            httpGet:
              path: /auth
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 60
          volumeMounts:
          - mountPath: /opt/jboss/keycloak/standalone/configuration/import
            name: keycloak-subst-config
          - mountPath: /opt/jboss/keycloak/themes/fabric8
            name: keycloak-theme
        volumes:
        - emptyDir: {}
          name: keycloak-subst-config
        - configMap:
            items:
            - key: realm.json
              path: config/realm.json
            name: {{ template "name" . }}
          name: keycloak-config
        - gitRepo:
            directory: login
            repository: https://github.com/fabric8io/fabric8-keycloak-theme.git
            revision: 61b08f0a2f4be2395bb0bbb6d16a8538f4f2b836
          name: keycloak-theme
