---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}
  data:
    db.host: {{ .Values.keycloak.config.database.host }}
    db.name: {{ .Values.keycloak.config.database.name }}
    db.user: {{ .Values.keycloak.config.database.username }}
    db.password: {{ .Values.keycloak.config.database.password }}
    kc.user: {{ .Values.keycloak.config.user }}
    kc.password: {{ .Values.keycloak.config.password }}
    kc.clientid.secret: {{ .Values.keycloak.config.clientSecret }}
    kc.private.key: {{ .Values.keycloak.config.privateKey }}
    kc.public.key: {{ .Values.keycloak.config.publicKey }}
