---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/ingress.annotations: |-
        ingress.kubernetes.io/force-ssl-redirect: {{ .Values.keycloak.service.forceSslRedirect }}
        kubernetes.io/ingress.class: {{ .Values.keycloak.service.ingressClass }}
      {{- with .Values.keycloak.forecastle.expose }}
        forecastle.stakater.com/expose: {{ . }}
      {{- end }}
      {{- with .Values.keycloak.forecastle.icon }}
        forecastle.stakater.com/icon: {{ . }}
      {{- end }}
    labels:
      expose: "true"
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
{{ include "labels.selector" . | indent 6 }}