---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
{{- if .Values.keycloak.service.annotations }}
    annotations:
{{ toYaml .Values.keycloak.service.annotations | indent 6 }}
{{- end }}
    labels:
      expose: "true"
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
{{ include "labels.selector" . | indent 6 }}